server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driveClassName: com.mysql.jdbc.Driver
jpa:
  show-sql: true
  hibernate:
    naming:
      implicitStrategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      physicalStrategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl